- name: run report tasks
  hosts: all
  gather_facts: False

  # variables passed from AWX job survey:

  # {{ rds_db }}
  # {{ rds_host }}
  # {{ rds_pass }}
  # {{ rds_user }}

  environment:

    RDS_DB: "{{ rds_db }}"
    RDS_HOST: "{{ rds_host }}"
    RDS_PASS: "{{ rds_pass }}"
    RDS_USER: "{{ rds_user }}"

  pre_tasks:

    - name: pip
      block:

        - name: install mysql-client
          package:
            name: mysql
            state: present
          become: true

  tasks:
    
    - name: vars
      block:

        - include_vars: vars/sql.yaml

    - name: total
      block:

        # - name: run total report
        #   docker_container:
        #     name: ambi_vault_billing_total_report
        #     image: mysql:5.7
        #     command: sh -c "exec mysql -h${RDS_HOST} -P3306 -u${RDS_USER} -p${RDS_PASS} -e \"{{ sql_query_total }}\" ${RDS_PASS}"
        #     state: started
        #     restart: no
        #     auto_remove: no
        #     env:
        #       RDS_HOST: "{{ rds_host }}"
        #       RDS_DB: "{{ rds_db }}"
        #       RDS_USER: "{{ rds_user }}"
        #       RDS_PASS: "{{ rds_pass }}"
        #   register: total_report

        - name: run total report
          command: mysql -h {{ rds_host }} -u {{ rds_user }} -p{{ rds_pass }} -e "{{ sql_query_total }}" {{ rds_db }} | sed "s/\t/,/g;" > /tmp/total.csv
          register: total_report

        - debug:
            var: total_report.stdout

        - name: run org address report
          command: mysql -h {{ rds_host }} -u {{ rds_user }} -p{{ rds_pass }} -e "{{ sql_query_org_address }}" {{ rds_db }} | sed "s/\t/,/g;" > /tmp/org_address.csv
          register: org_report

        - debug:
            var: org_report.stdout

        - name: run active users report
          command: mysql -h {{ rds_host }} -u {{ rds_user }} -p{{ rds_pass }} -e "{{ sql_query_active_users }}" {{ rds_db }} | sed "s/\t/,/g;" > /tmp/active_users.csv
          register: users_report

        - debug:
            var: users_report.stdout

        - file:
            path: /etc/foo.conf
            state: absent
          with_items:
            - /tmp/total.csv
            - /tmp/org_address.csv
            - /tmp/active_users.csv